---
- name: Send Email with HTML Attachment
  hosts: group1-og
  gather_facts: yes
  vars_files:
    - vars/email_config.yml
  
  tasks:

 #   - name: Get all hosts facts
 #     debug:
 #       var: hostvars

    - name: Create consolidated HTML report for all hosts
      template:
        src: templates/email-report.html.j2
        dest: "/tmp/email-report-consolidated.html"
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: Send email with HTML attachment
      community.general.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ email_to }}"
        from: "{{ email_from }}"
        subject: "{{ email_subject }}"
        body: "{{ email_body }}"
        attach: "/tmp/email-report-consolidated.html"
        secure: "{{ smtp_secure }}"
      delegate_to: localhost
      run_once: true

    - name: Clean up temporary HTML file
      file:
        path: "/tmp/email-report-consolidated.html"
        state: absent
      delegate_to: localhost
      run_once: true
